config/routes.rb
Rails.application.routes.draw do
  get 'top', to: 'top#index'

  resources :gadgets
  resources :works

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :work
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :set_gadget, only: [:show, :edit, :update, :destroy]

  # GET /gadgets
  # GET /gadgets.json
  def index
    @gadgets = Gadget.all
  end

  # GET /gadgets/1
  # GET /gadgets/1.json
  def show
  end

  # GET /gadgets/new
  def new
    @gadget = Gadget.new
  end

  # GET /gadgets/1/edit
  def edit
  end

  # POST /gadgets
  # POST /gadgets.json
  def create
    @gadget = Gadget.new(gadget_params)

    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Gadget was successfully created.' }
        format.json { render :show, status: :created, location: @gadget }
      else
        format.html { render :new }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gadgets/1
  # PATCH/PUT /gadgets/1.json
  def update
    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Gadget was successfully updated.' }
        format.json { render :show, status: :ok, location: @gadget }
      else
        format.html { render :edit }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gadgets/1
  # DELETE /gadgets/1.json
  def destroy
    @gadget.destroy
    respond_to do |format|
      format.html { redirect_to gadgets_url, notice: 'Gadget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gadget
      @gadget = Gadget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gadget_params
      params.require(:gadget).permit(:name, :work_id, :description)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @works = Work.all.order("id desc").limit(5)
    @gadgets = Gadget.includes(:work).all.order("id desc").limit(5)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/gadgets/_form.html.erb
<%= form_for(gadget) do |f| %>
  <% if gadget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gadget.errors.count, "error") %> prohibited this gadget from being saved:</h2>

      <ul>
      <% gadget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :work_id %>
    <%= f.number_field :work_id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gadgets/edit.html.erb
<h1>Editing Gadget</h1>

<%= render 'form', gadget: @gadget %>

<%= link_to 'Show', @gadget %> |
<%= link_to 'Back', gadgets_path %>

app/views/gadgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gadgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Work</th>
      <th>Discription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gadgets.each do |gadget| %>
      <tr>
        <td><%= gadget.name %></td>
        <td><%= gadget.work_id %></td>
        <td><%= gadget.description %></td>
        <td><%= link_to 'Show', gadget %></td>
        <td><%= link_to 'Edit', edit_gadget_path(gadget) %></td>
        <td><%= link_to 'Destroy', gadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gadget', new_gadget_path %>

app/views/gadgets/new.html.erb
<h1>New Gadget</h1>

<%= render 'form', gadget: @gadget %>

<%= link_to 'Back', gadgets_path %>

app/views/gadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gadget.name %>
</p>

<p>
  <strong>Work:</strong>
  <%= @gadget.work_id %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @gadget.description %>
</p>

<%= link_to 'Edit', edit_gadget_path(@gadget) %> |
<%= link_to 'Back', gadgets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gadgets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>SFガジェット図鑑</h1>

<h2>最近登録した作品</h2>

<% @works.each do |work| %>
<%= link_to(work.name, work_path(work.id)) %>
<br />
<% end %>

<h2>最近登録したガジェット</h2>

<% @gadgets.each do |gadget| %>
<%= link_to(gadget.name, gadget_path(gadget.id)) %>
<br />
<% end %>

app/views/works/_form.html.erb
<%= form_for(work) do |f| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Discription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= work.description %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @work.description %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>